[target.thumbv7m-none-eabi]
runner = 'probe-rs run --chip STM32F103C8Tx'
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "panic=abort",
  #"-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"

[profile.release]
opt-level = 3
